// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: deltaswap/events.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventPhylaxSetUpdate struct {
	OldIndex uint32 `protobuf:"varint,1,opt,name=old_index,json=oldIndex,proto3" json:"old_index,omitempty"`
	NewIndex uint32 `protobuf:"varint,2,opt,name=new_index,json=newIndex,proto3" json:"new_index,omitempty"`
}

func (m *EventPhylaxSetUpdate) Reset()         { *m = EventPhylaxSetUpdate{} }
func (m *EventPhylaxSetUpdate) String() string { return proto.CompactTextString(m) }
func (*EventPhylaxSetUpdate) ProtoMessage()    {}
func (*EventPhylaxSetUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_489a4684a580eb5a, []int{0}
}
func (m *EventPhylaxSetUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPhylaxSetUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPhylaxSetUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPhylaxSetUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPhylaxSetUpdate.Merge(m, src)
}
func (m *EventPhylaxSetUpdate) XXX_Size() int {
	return m.Size()
}
func (m *EventPhylaxSetUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPhylaxSetUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_EventPhylaxSetUpdate proto.InternalMessageInfo

func (m *EventPhylaxSetUpdate) GetOldIndex() uint32 {
	if m != nil {
		return m.OldIndex
	}
	return 0
}

func (m *EventPhylaxSetUpdate) GetNewIndex() uint32 {
	if m != nil {
		return m.NewIndex
	}
	return 0
}

type EventPostedMessage struct {
	Emitter  []byte `protobuf:"bytes,1,opt,name=emitter,proto3" json:"emitter,omitempty"`
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Nonce    uint32 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Time     uint64 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Payload  []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *EventPostedMessage) Reset()         { *m = EventPostedMessage{} }
func (m *EventPostedMessage) String() string { return proto.CompactTextString(m) }
func (*EventPostedMessage) ProtoMessage()    {}
func (*EventPostedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_489a4684a580eb5a, []int{1}
}
func (m *EventPostedMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPostedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPostedMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPostedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPostedMessage.Merge(m, src)
}
func (m *EventPostedMessage) XXX_Size() int {
	return m.Size()
}
func (m *EventPostedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPostedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventPostedMessage proto.InternalMessageInfo

func (m *EventPostedMessage) GetEmitter() []byte {
	if m != nil {
		return m.Emitter
	}
	return nil
}

func (m *EventPostedMessage) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *EventPostedMessage) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *EventPostedMessage) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *EventPostedMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EventPhylaxRegistered struct {
	PhylaxKey    []byte `protobuf:"bytes,1,opt,name=phylax_key,json=phylaxKey,proto3" json:"phylax_key,omitempty"`
	ValidatorKey []byte `protobuf:"bytes,2,opt,name=validator_key,json=validatorKey,proto3" json:"validator_key,omitempty"`
}

func (m *EventPhylaxRegistered) Reset()         { *m = EventPhylaxRegistered{} }
func (m *EventPhylaxRegistered) String() string { return proto.CompactTextString(m) }
func (*EventPhylaxRegistered) ProtoMessage()    {}
func (*EventPhylaxRegistered) Descriptor() ([]byte, []int) {
	return fileDescriptor_489a4684a580eb5a, []int{2}
}
func (m *EventPhylaxRegistered) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPhylaxRegistered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPhylaxRegistered.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPhylaxRegistered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPhylaxRegistered.Merge(m, src)
}
func (m *EventPhylaxRegistered) XXX_Size() int {
	return m.Size()
}
func (m *EventPhylaxRegistered) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPhylaxRegistered.DiscardUnknown(m)
}

var xxx_messageInfo_EventPhylaxRegistered proto.InternalMessageInfo

func (m *EventPhylaxRegistered) GetPhylaxKey() []byte {
	if m != nil {
		return m.PhylaxKey
	}
	return nil
}

func (m *EventPhylaxRegistered) GetValidatorKey() []byte {
	if m != nil {
		return m.ValidatorKey
	}
	return nil
}

type EventConsensusSetUpdate struct {
	OldIndex uint32 `protobuf:"varint,1,opt,name=old_index,json=oldIndex,proto3" json:"old_index,omitempty"`
	NewIndex uint32 `protobuf:"varint,2,opt,name=new_index,json=newIndex,proto3" json:"new_index,omitempty"`
}

func (m *EventConsensusSetUpdate) Reset()         { *m = EventConsensusSetUpdate{} }
func (m *EventConsensusSetUpdate) String() string { return proto.CompactTextString(m) }
func (*EventConsensusSetUpdate) ProtoMessage()    {}
func (*EventConsensusSetUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_489a4684a580eb5a, []int{3}
}
func (m *EventConsensusSetUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventConsensusSetUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventConsensusSetUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventConsensusSetUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventConsensusSetUpdate.Merge(m, src)
}
func (m *EventConsensusSetUpdate) XXX_Size() int {
	return m.Size()
}
func (m *EventConsensusSetUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_EventConsensusSetUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_EventConsensusSetUpdate proto.InternalMessageInfo

func (m *EventConsensusSetUpdate) GetOldIndex() uint32 {
	if m != nil {
		return m.OldIndex
	}
	return 0
}

func (m *EventConsensusSetUpdate) GetNewIndex() uint32 {
	if m != nil {
		return m.NewIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*EventPhylaxSetUpdate)(nil), "deltaswapio.deltachain.deltaswap.EventPhylaxSetUpdate")
	proto.RegisterType((*EventPostedMessage)(nil), "deltaswapio.deltachain.deltaswap.EventPostedMessage")
	proto.RegisterType((*EventPhylaxRegistered)(nil), "deltaswapio.deltachain.deltaswap.EventPhylaxRegistered")
	proto.RegisterType((*EventConsensusSetUpdate)(nil), "deltaswapio.deltachain.deltaswap.EventConsensusSetUpdate")
}

func init() { proto.RegisterFile("deltaswap/events.proto", fileDescriptor_489a4684a580eb5a) }

var fileDescriptor_489a4684a580eb5a = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0x29, 0x17, 0xee, 0x85, 0x13, 0xd8, 0x4c, 0xb8, 0xda, 0x68, 0x6c, 0x48, 0xdd, 0xb8,
	0x6a, 0x17, 0xbc, 0x81, 0xc6, 0x85, 0x21, 0x24, 0xa4, 0xc4, 0x8d, 0x2e, 0xc8, 0xc0, 0x9c, 0xc0,
	0xc4, 0x32, 0x53, 0x3b, 0x87, 0x3f, 0x7d, 0x09, 0xe3, 0x63, 0xb9, 0x64, 0xe9, 0xd2, 0xc0, 0x8b,
	0x98, 0x4e, 0xb1, 0xf0, 0x00, 0xee, 0xce, 0xf7, 0x7d, 0x67, 0x7e, 0xf3, 0xe7, 0x0c, 0x9c, 0x09,
	0x8c, 0x89, 0x9b, 0x35, 0x4f, 0x42, 0x5c, 0xa1, 0x22, 0x13, 0x24, 0xa9, 0x26, 0xcd, 0xba, 0xa5,
	0x2f, 0x75, 0x60, 0xeb, 0xe9, 0x9c, 0x4b, 0x15, 0x94, 0xb6, 0x3f, 0x84, 0xce, 0x7d, 0xbe, 0x62,
	0x38, 0xcf, 0x62, 0xbe, 0x19, 0x21, 0x3d, 0x26, 0x82, 0x13, 0xb2, 0x4b, 0x68, 0xea, 0x58, 0x8c,
	0xa5, 0x12, 0xb8, 0x71, 0x9d, 0xae, 0x73, 0xd3, 0x8e, 0x1a, 0x3a, 0x16, 0x0f, 0xb9, 0xce, 0x43,
	0x85, 0xeb, 0x43, 0x58, 0x2d, 0x42, 0x85, 0x6b, 0x1b, 0xfa, 0x6f, 0x0e, 0xb0, 0x02, 0xa9, 0x0d,
	0xa1, 0x18, 0xa0, 0x31, 0x7c, 0x86, 0xcc, 0x85, 0x7f, 0xb8, 0x90, 0x44, 0x98, 0x5a, 0x5c, 0x2b,
	0xfa, 0x91, 0xec, 0x02, 0x1a, 0x06, 0x5f, 0x97, 0xa8, 0xa6, 0x68, 0x61, 0xb5, 0xa8, 0xd4, 0xac,
	0x03, 0x75, 0xa5, 0xf3, 0xe0, 0x8f, 0xdd, 0xa5, 0x10, 0x8c, 0x41, 0x8d, 0xe4, 0x02, 0xdd, 0x9a,
	0xed, 0xb6, 0x75, 0xce, 0x4f, 0x78, 0x16, 0x6b, 0x2e, 0xdc, 0x7a, 0xc1, 0x3f, 0x48, 0xff, 0x19,
	0xfe, 0x9f, 0x5c, 0x31, 0xc2, 0x99, 0x34, 0x84, 0x29, 0x0a, 0x76, 0x05, 0x90, 0x58, 0x6f, 0xfc,
	0x82, 0xd9, 0xe1, 0x54, 0xcd, 0xc2, 0xe9, 0x63, 0xc6, 0xae, 0xa1, 0xbd, 0xe2, 0xb1, 0x14, 0x9c,
	0x74, 0x6a, 0x3b, 0xaa, 0xb6, 0xa3, 0x55, 0x9a, 0x7d, 0xcc, 0xfc, 0x11, 0x9c, 0x5b, 0xf8, 0x9d,
	0x56, 0x06, 0x95, 0x59, 0x9a, 0x5f, 0x78, 0xc2, 0xdb, 0xc1, 0xc7, 0xce, 0x73, 0xb6, 0x3b, 0xcf,
	0xf9, 0xda, 0x79, 0xce, 0xfb, 0xde, 0xab, 0x6c, 0xf7, 0x5e, 0xe5, 0x73, 0xef, 0x55, 0x9e, 0x7a,
	0x33, 0x49, 0xf3, 0xe5, 0x24, 0x98, 0xea, 0x45, 0x78, 0x32, 0xdb, 0xf0, 0x38, 0xdb, 0x70, 0x73,
	0x0c, 0x42, 0xca, 0x12, 0x34, 0x93, 0xbf, 0xf6, 0x33, 0xf4, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xbb, 0x9b, 0xe4, 0xa1, 0x26, 0x02, 0x00, 0x00,
}

func (m *EventPhylaxSetUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPhylaxSetUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPhylaxSetUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewIndex != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.NewIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.OldIndex != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.OldIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventPostedMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPostedMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPostedMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Time != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x20
	}
	if m.Nonce != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x18
	}
	if m.Sequence != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Emitter) > 0 {
		i -= len(m.Emitter)
		copy(dAtA[i:], m.Emitter)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Emitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventPhylaxRegistered) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPhylaxRegistered) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPhylaxRegistered) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorKey) > 0 {
		i -= len(m.ValidatorKey)
		copy(dAtA[i:], m.ValidatorKey)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ValidatorKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PhylaxKey) > 0 {
		i -= len(m.PhylaxKey)
		copy(dAtA[i:], m.PhylaxKey)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.PhylaxKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventConsensusSetUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventConsensusSetUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventConsensusSetUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewIndex != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.NewIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.OldIndex != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.OldIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventPhylaxSetUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OldIndex != 0 {
		n += 1 + sovEvents(uint64(m.OldIndex))
	}
	if m.NewIndex != 0 {
		n += 1 + sovEvents(uint64(m.NewIndex))
	}
	return n
}

func (m *EventPostedMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Emitter)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Sequence != 0 {
		n += 1 + sovEvents(uint64(m.Sequence))
	}
	if m.Nonce != 0 {
		n += 1 + sovEvents(uint64(m.Nonce))
	}
	if m.Time != 0 {
		n += 1 + sovEvents(uint64(m.Time))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventPhylaxRegistered) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PhylaxKey)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ValidatorKey)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventConsensusSetUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OldIndex != 0 {
		n += 1 + sovEvents(uint64(m.OldIndex))
	}
	if m.NewIndex != 0 {
		n += 1 + sovEvents(uint64(m.NewIndex))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventPhylaxSetUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPhylaxSetUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPhylaxSetUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldIndex", wireType)
			}
			m.OldIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewIndex", wireType)
			}
			m.NewIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventPostedMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPostedMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPostedMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Emitter", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Emitter = append(m.Emitter[:0], dAtA[iNdEx:postIndex]...)
			if m.Emitter == nil {
				m.Emitter = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventPhylaxRegistered) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPhylaxRegistered: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPhylaxRegistered: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhylaxKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PhylaxKey = append(m.PhylaxKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PhylaxKey == nil {
				m.PhylaxKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorKey = append(m.ValidatorKey[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorKey == nil {
				m.ValidatorKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventConsensusSetUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventConsensusSetUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventConsensusSetUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldIndex", wireType)
			}
			m.OldIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewIndex", wireType)
			}
			m.NewIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
