// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: deltaswap/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the deltaswap module's genesis state.
type GenesisState struct {
	PhylaxSetList              []PhylaxSet                            `protobuf:"bytes,1,rep,name=phylaxSetList,proto3" json:"phylaxSetList"`
	Config                     *Config                                `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	ReplayProtectionList       []ReplayProtection                     `protobuf:"bytes,3,rep,name=replayProtectionList,proto3" json:"replayProtectionList"`
	SequenceCounterList        []SequenceCounter                      `protobuf:"bytes,4,rep,name=sequenceCounterList,proto3" json:"sequenceCounterList"`
	ConsensusPhylaxSetIndex    *ConsensusPhylaxSetIndex               `protobuf:"bytes,5,opt,name=consensusPhylaxSetIndex,proto3" json:"consensusPhylaxSetIndex,omitempty"`
	PhylaxValidatorList        []PhylaxValidator                      `protobuf:"bytes,6,rep,name=phylaxValidatorList,proto3" json:"phylaxValidatorList"`
	AllowedAddresses           []ValidatorAllowedAddress              `protobuf:"bytes,7,rep,name=allowedAddresses,proto3" json:"allowedAddresses"`
	WasmInstantiateAllowlist   []WasmInstantiateAllowedContractCodeId `protobuf:"bytes,8,rep,name=wasmInstantiateAllowlist,proto3" json:"wasmInstantiateAllowlist"`
	IbcComposabilityMwContract IbcComposabilityMwContract             `protobuf:"bytes,9,opt,name=ibcComposabilityMwContract,proto3" json:"ibcComposabilityMwContract"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d47eeb1fd458fd0, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetPhylaxSetList() []PhylaxSet {
	if m != nil {
		return m.PhylaxSetList
	}
	return nil
}

func (m *GenesisState) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *GenesisState) GetReplayProtectionList() []ReplayProtection {
	if m != nil {
		return m.ReplayProtectionList
	}
	return nil
}

func (m *GenesisState) GetSequenceCounterList() []SequenceCounter {
	if m != nil {
		return m.SequenceCounterList
	}
	return nil
}

func (m *GenesisState) GetConsensusPhylaxSetIndex() *ConsensusPhylaxSetIndex {
	if m != nil {
		return m.ConsensusPhylaxSetIndex
	}
	return nil
}

func (m *GenesisState) GetPhylaxValidatorList() []PhylaxValidator {
	if m != nil {
		return m.PhylaxValidatorList
	}
	return nil
}

func (m *GenesisState) GetAllowedAddresses() []ValidatorAllowedAddress {
	if m != nil {
		return m.AllowedAddresses
	}
	return nil
}

func (m *GenesisState) GetWasmInstantiateAllowlist() []WasmInstantiateAllowedContractCodeId {
	if m != nil {
		return m.WasmInstantiateAllowlist
	}
	return nil
}

func (m *GenesisState) GetIbcComposabilityMwContract() IbcComposabilityMwContract {
	if m != nil {
		return m.IbcComposabilityMwContract
	}
	return IbcComposabilityMwContract{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "deltaswapio.deltachain.deltaswap.GenesisState")
}

func init() { proto.RegisterFile("deltaswap/genesis.proto", fileDescriptor_0d47eeb1fd458fd0) }

var fileDescriptor_0d47eeb1fd458fd0 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x8b, 0xd3, 0x4e,
	0x18, 0xc6, 0x9b, 0xef, 0xee, 0xb7, 0xab, 0xb3, 0x0a, 0x12, 0x17, 0x37, 0xec, 0x21, 0x56, 0x4f,
	0x45, 0x21, 0xc1, 0xee, 0x49, 0xf0, 0xe0, 0x6e, 0x40, 0x29, 0xb8, 0x50, 0x5a, 0x70, 0xc1, 0x4b,
	0x98, 0x26, 0xaf, 0xe9, 0x60, 0x3a, 0x13, 0x33, 0x6f, 0xe9, 0xf6, 0xea, 0xc9, 0xa3, 0x7f, 0xd6,
	0x1e, 0xf7, 0xe8, 0x49, 0xa5, 0xfd, 0x47, 0x24, 0x33, 0xf9, 0xb1, 0xd1, 0xd4, 0xf4, 0x36, 0xbc,
	0x99, 0xe7, 0xf3, 0x3c, 0xef, 0x33, 0x10, 0x72, 0x1c, 0x42, 0x8c, 0x54, 0x2e, 0x69, 0xe2, 0x46,
	0xc0, 0x41, 0x32, 0xe9, 0x24, 0xa9, 0x40, 0x61, 0xf6, 0xca, 0x0f, 0x4c, 0x38, 0xea, 0x1c, 0xcc,
	0x28, 0xe3, 0x4e, 0x39, 0x3e, 0x79, 0x54, 0x49, 0x93, 0xd9, 0x2a, 0xa6, 0x57, 0x5a, 0x79, 0x7b,
	0x1e, 0x08, 0xfe, 0x91, 0x45, 0xf9, 0xfc, 0x49, 0x35, 0x4f, 0x21, 0x89, 0xe9, 0xca, 0xcf, 0xe6,
	0x10, 0x20, 0x13, 0x3c, 0xbf, 0x52, 0x99, 0xba, 0x12, 0x3e, 0x2f, 0x80, 0x07, 0xe0, 0x07, 0x62,
	0xc1, 0x11, 0xd2, 0xfc, 0xc6, 0xb3, 0x1a, 0x5c, 0x02, 0x97, 0x0b, 0xe9, 0x6b, 0x7b, 0x5f, 0x02,
	0xfa, 0x8c, 0x87, 0x50, 0x04, 0x39, 0x8a, 0x44, 0x24, 0xd4, 0xd1, 0xcd, 0x4e, 0x7a, 0xfa, 0xf4,
	0xe7, 0x01, 0xb9, 0xf7, 0x56, 0xaf, 0x3a, 0x41, 0x8a, 0x60, 0x5e, 0x92, 0xfb, 0x1a, 0x30, 0x01,
	0x7c, 0xc7, 0x24, 0x5a, 0x46, 0x6f, 0xaf, 0x7f, 0x38, 0x78, 0xee, 0xb4, 0x35, 0xe0, 0x8c, 0x0a,
	0xd9, 0xf9, 0xfe, 0xf5, 0x8f, 0xc7, 0x9d, 0x71, 0x9d, 0x63, 0xbe, 0x26, 0x5d, 0x5d, 0x80, 0xf5,
	0x5f, 0xcf, 0xe8, 0x1f, 0x0e, 0xfa, 0xed, 0x44, 0x4f, 0xdd, 0x1f, 0xe7, 0x3a, 0x33, 0x26, 0x47,
	0xba, 0xaa, 0x51, 0xd9, 0x94, 0x4a, 0xb8, 0xa7, 0x12, 0x0e, 0xda, 0x79, 0xe3, 0x3f, 0xd4, 0x79,
	0xd0, 0x46, 0xaa, 0xc9, 0xc8, 0xc3, 0xa2, 0x75, 0x4f, 0x97, 0xae, 0xcc, 0xf6, 0x95, 0xd9, 0x8b,
	0x76, 0xb3, 0x49, 0x5d, 0x9c, 0x7b, 0x35, 0x31, 0x4d, 0x49, 0x8e, 0xcb, 0xe7, 0x2b, 0x5b, 0x1c,
	0x66, 0x6f, 0x67, 0xfd, 0xaf, 0xba, 0x7a, 0xb9, 0x53, 0x57, 0x4d, 0x80, 0xf1, 0x36, 0x72, 0xb6,
	0x9f, 0x7e, 0xa0, 0xf7, 0x34, 0x66, 0x21, 0x45, 0xa1, 0xf7, 0xeb, 0xee, 0xba, 0xdf, 0xa8, 0x2e,
	0x2e, 0xf6, 0x6b, 0x60, 0x9a, 0x9f, 0xc8, 0x03, 0x1a, 0xc7, 0x62, 0x09, 0xe1, 0x59, 0x18, 0xa6,
	0x20, 0x25, 0x48, 0xeb, 0x40, 0xf9, 0xec, 0xb0, 0x58, 0x89, 0x3a, 0xab, 0x21, 0x72, 0xbf, 0xbf,
	0xc0, 0xe6, 0x57, 0x83, 0x58, 0x4b, 0x2a, 0xe7, 0x43, 0x2e, 0x91, 0x72, 0x64, 0x14, 0x41, 0x29,
	0xe3, 0x6c, 0xbb, 0x3b, 0xca, 0xf5, 0x4d, 0xbb, 0xeb, 0x65, 0x03, 0x01, 0x42, 0x4f, 0x70, 0x4c,
	0x69, 0x80, 0x9e, 0x08, 0x61, 0x18, 0xe6, 0x11, 0xb6, 0xba, 0x99, 0x5f, 0x0c, 0x72, 0xc2, 0xa6,
	0x81, 0x27, 0xe6, 0x89, 0x90, 0x74, 0xca, 0x62, 0x86, 0xab, 0x8b, 0x65, 0x01, 0xb1, 0xee, 0xaa,
	0xb7, 0x7d, 0xd5, 0x1e, 0x66, 0xb8, 0x95, 0x91, 0x47, 0xf8, 0x87, 0xcb, 0xf9, 0xc5, 0xf5, 0xda,
	0x36, 0x6e, 0xd6, 0xb6, 0xf1, 0x6b, 0x6d, 0x1b, 0xdf, 0x36, 0x76, 0xe7, 0x66, 0x63, 0x77, 0xbe,
	0x6f, 0xec, 0xce, 0x87, 0xd3, 0x88, 0xe1, 0x6c, 0x31, 0x75, 0x02, 0x31, 0x77, 0x6f, 0x65, 0x70,
	0xab, 0x0c, 0xee, 0x55, 0xf5, 0xc1, 0xc5, 0x55, 0x02, 0x72, 0xda, 0x55, 0xff, 0x8d, 0xd3, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x5f, 0x5f, 0x79, 0x2b, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.IbcComposabilityMwContract.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if len(m.WasmInstantiateAllowlist) > 0 {
		for iNdEx := len(m.WasmInstantiateAllowlist) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WasmInstantiateAllowlist[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.AllowedAddresses) > 0 {
		for iNdEx := len(m.AllowedAddresses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllowedAddresses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.PhylaxValidatorList) > 0 {
		for iNdEx := len(m.PhylaxValidatorList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PhylaxValidatorList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.ConsensusPhylaxSetIndex != nil {
		{
			size, err := m.ConsensusPhylaxSetIndex.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SequenceCounterList) > 0 {
		for iNdEx := len(m.SequenceCounterList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SequenceCounterList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ReplayProtectionList) > 0 {
		for iNdEx := len(m.ReplayProtectionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReplayProtectionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Config != nil {
		{
			size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PhylaxSetList) > 0 {
		for iNdEx := len(m.PhylaxSetList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PhylaxSetList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PhylaxSetList) > 0 {
		for _, e := range m.PhylaxSetList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Config != nil {
		l = m.Config.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.ReplayProtectionList) > 0 {
		for _, e := range m.ReplayProtectionList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SequenceCounterList) > 0 {
		for _, e := range m.SequenceCounterList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ConsensusPhylaxSetIndex != nil {
		l = m.ConsensusPhylaxSetIndex.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.PhylaxValidatorList) > 0 {
		for _, e := range m.PhylaxValidatorList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AllowedAddresses) > 0 {
		for _, e := range m.AllowedAddresses {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WasmInstantiateAllowlist) > 0 {
		for _, e := range m.WasmInstantiateAllowlist {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.IbcComposabilityMwContract.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhylaxSetList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PhylaxSetList = append(m.PhylaxSetList, PhylaxSet{})
			if err := m.PhylaxSetList[len(m.PhylaxSetList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Config == nil {
				m.Config = &Config{}
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplayProtectionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReplayProtectionList = append(m.ReplayProtectionList, ReplayProtection{})
			if err := m.ReplayProtectionList[len(m.ReplayProtectionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceCounterList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SequenceCounterList = append(m.SequenceCounterList, SequenceCounter{})
			if err := m.SequenceCounterList[len(m.SequenceCounterList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPhylaxSetIndex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusPhylaxSetIndex == nil {
				m.ConsensusPhylaxSetIndex = &ConsensusPhylaxSetIndex{}
			}
			if err := m.ConsensusPhylaxSetIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhylaxValidatorList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PhylaxValidatorList = append(m.PhylaxValidatorList, PhylaxValidator{})
			if err := m.PhylaxValidatorList[len(m.PhylaxValidatorList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAddresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedAddresses = append(m.AllowedAddresses, ValidatorAllowedAddress{})
			if err := m.AllowedAddresses[len(m.AllowedAddresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmInstantiateAllowlist", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WasmInstantiateAllowlist = append(m.WasmInstantiateAllowlist, WasmInstantiateAllowedContractCodeId{})
			if err := m.WasmInstantiateAllowlist[len(m.WasmInstantiateAllowlist)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcComposabilityMwContract", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IbcComposabilityMwContract.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
